---
title: "Leaflet"
author: "Ashlee, Margarita, Jocelyn, and Rob"
date: "4/12/2022"
output: html_document
---


# Base Map
Creating a standard basemap 

```{r, warning=FALSE, message=FALSE}

standard.basemap <- leaflet() %>% # leaflet 
 addTiles() %>% 
setView(lat= 37.5, lng=-95.5, zoom=3)

standard.basemap

```

Creating third-party basemaps can be done by searching for different colors and styles of map tiles. 
```{r}

blackandwhite.basemap <- standard.basemap %>% # leaflet 
addProviderTiles(providers$Stamen.Toner)

cartoon.basemap <- standard.basemap %>% # leaflet 
addProviderTiles(providers$CartoDB.Positron)

```

Combining Tile Layers 


```{r}

 standard.basemap %>% 
  addProviderTiles(providers$Stamen.TonerLines,
    options = providerTileOptions(opacity = 0.35)) %>%
  addProviderTiles(providers$Stamen.TonerLabels)


```

Adding Markers

```{r}

longitude <- data$longitude
latitude <- data$latitude
volcanonames <- data$volcano_name

m <- standard.basemap %>% 
addMarkers(lng = longitude, lat = latitude, popup = volcanonames) # add a single point layer
m

 standard.basemap


```

